### ISSUE TITLE
cannot find symbol method toHashMap()

### ISSUE THREAD

**Issue by beyerss** [getsentry/react-native-sentry#161]
Hi,

I have just installed sentry into my RN app and when I try to build in Android Studio I get an error that says "cannot find symbol method toHashMap()". The error is coming from RNSentryModule.java. Can anyone tell me whats going on here?

**Comment by HazAT** [comment]
Hey,
I'm currently looking into this, this shouldn't happen.

**Comment by HazAT** [comment]
Can you tell the line number? 
And what kind of breadcrumb you are trying to set?

**Comment by beyerss** [comment]
line 171 and I'm not (intentionally) sending anything yet. I only followed the setup instructions by adding sentry to my RN project then ran the link command and configured sentry through the prompts. After that I tried to build and run the app to make sure I did everything properly but the app won't build.

The only code that was added was whatever the install/setup process does. I'm not sure if that auto-sets any breadcrumbs.

**Comment by beyerss** [comment]
<img width="386" alt="screen shot 2017-07-21 at 8 56 15 am" src="https://user-images.githubusercontent.com/1074621/28464297-80dc757a-6df2-11e7-8aed-06a110a4e378.png">

If it is helpful, this is the interface that I see for the ReadableMap class. Clearly, there is no toHashMap() there.

**Comment by HazAT** [comment]
Hmm, that's really strange.
There must be something wrong with you react-native installation.
Because it's there in the repo, 
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableMap.java

**Comment by beyerss** [comment]
That is it - I'm on RN v0.45.1 but it looks like toHashMap was added in v0.46.

Thanks!

**Comment by HazAT** [comment]
OK, we were actually using `toHashMap` since the first version.
Strange that it occurs now.

**Comment by jonolock91** [comment]
I'm also getting this issue now, I've not long upgraded to RN 0.44.0 and using the latest version of this library. It compiled recently I'm not sure what's changed...

**Comment by jonolock91** [comment]
@HazAT I'm still having this issue with RN 0.44.0, any ideas why this might be? I've checked the linked file you put above and the toHashMap does exist on mine. I was on version 0.41.0 but recently upgraded.

**Comment by HazAT** [comment]
@jonolock91 Please upgrade to `0.14.10` this should be fixed now.

**Comment by jonolock91** [comment]
@HazAT I've just tried that this morning but still the same error. I've re-installed all my node modules too. any other suggestions? I'm using:
```
"react": "16.0.0-alpha.6",
"react-native": "^0.44.1",
"react-native-sentry": "^0.14.9"
```

**Comment by jonolock91** [comment]
Sorry I misread that, 0.14.10 does fix my issue, thanks!
