### ISSUE TITLE
Crash information is sent again after every startup

### ISSUE THREAD

**Issue by vincejah** [getsentry/react-native-sentry#169]
Scenario:
A user has a crash with my application. it is successfully reported by Sentry. The crash is fixed on the next application release. On the first application run after the upgrade, the same crash is reported again (while it did not occur again). And worse, the reported software version is the new one. And this occurs at every software upgrade (on both Android and iOS)

I am using:
- react-native 0.44.3
- react-native_sentry 0.14.5

**Comment by HazAT** [comment]
So you are saying reports are sent twice?
Because I'm not sure why an upgrade to your app should retrigger sending the same report again.
Are you using CodePush?

**Comment by HazAT** [comment]
@vincejah I just fixed an issue that could be related to this.
Can you upgrade to `0.14.3` and see if it still occurs, you sounded like you can reproduce it easily.

**Comment by vincejah** [comment]
@HazAT it seems to have fixed the issue, but switching from 0.14.5 to 0.14.13 make native crash reporting not working (captureMessage and captureException are ok though)

**Comment by HazAT** [comment]
@vincejah `0.14.14` should address this.
Sorry for the inconvenience and thx for helping, I am currently looking into adding automated end-to-end tests so this does not happen anymore.

**Comment by vincejah** [comment]
@HazAT triggering a native crash with 0.14.14 prevents the application from exiting and crash report is still not sent

**Comment by HazAT** [comment]
I've reverted the changes, I am working on it want to get tests running first.
I will keep you posted. `0.14.15` reverted the changes.

**Comment by HazAT** [comment]
I've just released `0.15.0` which has tests for this issue. Please upgrade and report if you are still having trouble with this.

**Comment by vincejah** [comment]
@HazAT 
I have upgraded to v0.17.1 and I still get the issue. What I noticed is that at each application boot, it resends the same event (with different event_id though). Does it mean `sentry-buffered-events` is not properly cleaned after Raven sends an event?

You will see the codepush is installed but it is not used.

Here is my stacktrace:
```
08-18 11:16:58.923 23247 23280 D io.sentry.android.AndroidSentryClientFactory: Construction of Android Sentry.
08-18 11:16:58.924 23247 23279 I ReactNativeJS: 'react-native-sentry (setDataCallback):', [Function]
08-18 11:16:58.925 23247 23280 D io.sentry.android.AndroidSentryClientFactory: Sentry init with ctx='com.vtoupet.smartmixin.MainApplication@83e06d6' and dsn='Dsn{uri=https://sentry.io/}'
08-18 11:16:58.930 23247 23279 I ReactNativeJS: Running application "SmartMixin" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
08-18 11:16:58.974 23247 23280 D io.sentry.android.AndroidSentryClientFactory: Using buffer dir: /data/user/0/com.vtoupet.smartmixin/cache/sentry-buffered-events
08-18 11:16:58.986 23247 23280 I react-native-sentry: startWithDsnString 'https://439b7e0f40014850807c950bf19df002:eea11e718efb4a01a01eaa70b769aef9@sentry.io/164894'
08-18 11:16:58.987 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"react-native-sentry (setDataCallback): function (e) {console.log(e);var t=s.store.getState();return e.extra.app=t.app,e.extra.auth=t.auth,e.extra.user=t.user,e.extra.services=t.services,e;}","timestamp":1503047818.921} }'
08-18 11:16:58.991 23247 23279 I ReactNativeJS: [CodePush] Sync already in progress.
08-18 11:16:58.994 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"Running application \"SmartMixin\" with appParams: {\"initialProps\":{},\"rootTag\":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON","timestamp":1503047818.93} }'
08-18 11:16:59.004 23247 23280 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
08-18 11:16:59.024 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"[CodePush] Sync already in progress.","timestamp":1503047818.991} }'
08-18 11:16:59.085 23247 23279 D ReactNativeJS: 'Raven about to send:', { project: '164894',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:   logger: 'javascript',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:   platform: 'javascript',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:   request: {},
08-18 11:16:59.085 23247 23279 D ReactNativeJS:   exception: 
08-18 11:16:59.085 23247 23279 D ReactNativeJS:    { values: 
08-18 11:16:59.085 23247 23279 D ReactNativeJS:       [ { type: 'TypeError',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:           value: 'undefined is not a function (evaluating \'e.props.unknownProp()\')',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:           stacktrace: 
08-18 11:16:59.085 23247 23279 D ReactNativeJS:            { frames: 
08-18 11:16:59.085 23247 23279 D ReactNativeJS:               [ { filename: '[native code]',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   lineno: null,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   colno: null,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   function: '?',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   in_app: true },
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                 { filename: '/data/user/0/com.vtoupet.smartmixin/files/CodePush/fcee790bbc197889231a96be42defc895946cdec2ddb5ca21d9a97df81073a7e/android/index.android.bundle',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   lineno: 338,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   colno: 925,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   function: 'value',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   in_app: true },
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                 { filename: '/data/user/0/com.vtoupet.smartmixin/files/CodePush/fcee790bbc197889231a96be42defc895946cdec2ddb5ca21d9a97df81073a7e/android/index.android.bundle',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   lineno: 338,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   colno: 2413,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   function: 'value',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   in_app: true },
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                 { filename: '/data/user/0/com.vtoupet.smartmixin/files/CodePush/fcee790bbc197889231a96be42defc895946cdec2ddb5ca21d9a97df81073a7e/android/index.android.bundle',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   lineno: 338,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   colno: 953,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   function: '?',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   in_app: true },
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                 { filename: '/data/user/0/com.vtoupet.smartmixin/files/CodePush/fcee790bbc197889231a96be42defc895946cdec2ddb5ca21d9a97df81073a7e/android/index.android.bundle',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   lineno: 338,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   colno: 3012,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   function: 'value',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   in_app: true },
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                 { filename: '/data/user/0/com.vtoupet.smartmixin/files/CodePush/fcee790bbc197889231a96be42defc895946cdec2ddb5ca21d9a97df81073a7e/android/index.android.bundle',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   lineno: 465,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   colno: 921,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   function: 'receiveTouches',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   in_app: true },
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                 { filename: '/data/user/0/com.vtoupet.smartmixin/files/CodePush/fcee790bbc197889231a96be42defc895946cdec2ddb5ca21d9a97df81073a7e/android/index.android.bundle',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   lineno: 465,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   colno: 547,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   function: '_receiveRootNodeIDEvent',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   in_app: true },
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                 { filename: '/data/user/0/com.vtoupet.smartmixin/files/CodePush/fcee790bbc197889231a96be42defc895946cdec2ddb5ca21d9a97df81073a7e/android/index.android.bundle',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   lineno: 402,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   colno: 150,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   function: 'u',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   in_app: true },
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                 { filename: '/data/user/0/com.vtoupet.smartmixin/files/CodePush/fcee790bbc197889231a96be42defc895946cdec2ddb5ca21d9a97df81073a7e/android/index.android.bundle',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   lineno: 402,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   colno: 90,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   function: 'i',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   in_app: true },
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                 { filename: '/data/user/0/com.vtoupet.smartmixin/files/CodePush/fcee790bbc197889231a96be42defc895946cdec2ddb5ca21d9a97df81073a7e/android/index.android.bundle',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   lineno: 506,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   colno: 358,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   function: 'i',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   in_app: true },
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                 { filename: '/data/user/0/com.vtoupet.smartmixin/files/CodePush/fcee790bbc197889231a96be42defc895946cdec2ddb5ca21d9a97df81073a7e/android/index.android.bundle',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   lineno: 518,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   colno: 465,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   function: 'batchedUpdates',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   in_app: true },
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                 { filename: '/data/user/0/com.vtoupet.smartmixin/files/CodePush/fcee790bbc197889231a96be42defc895946cdec2ddb5ca21d9a97df81073a7e/android/index.android.bundle',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   lineno: 507,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   colno: 597,
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   function: 'perform',
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                   in_app: true },
08-18 11:16:59.085 23247 23279 D ReactNativeJS:                 { filename: '/data/user/0/com.vtoupet.smartmixin/files/CodePush/fcee790bbc197889231a96be42defc895946cdec2ddb5ca21d9a97df81073a7e/android/index.android.
08-18 11:16:59.086 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"level":"error","event_id":"6cb4ef5265464a1d920e9b363d229595","message":"TypeError: undefined is not a function (evaluating 'e.props.unknownProp()')","category":"sentry","timestamp":1503047819.085} }'
08-18 11:16:59.139 23247 23280 D io.sentry.android.event.helper.AndroidEventBuilderHelper: Proguard UUIDs file not found.
08-18 11:16:59.240 23247 23280 I react-native-sentry: addExtra '__sentry_version' 'codepush:v7'
08-18 11:16:59.241 23247 23279 I ReactNativeJS: [CodePush] Checking for update.
08-18 11:16:59.243 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"[CodePush] Checking for update.","timestamp":1503047819.24} }'
08-18 11:16:59.285 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"category":"fetch","type":"http","data":{"status_code":null,"url":"https://codepush.azurewebsites.net/updateCheck?deploymentKey=RLGAz3loD9CxGf0YaU0qBrFZLHCF8f04da60-90f7-443a-99a6-75aa62d73bad&appVersion=0.10.12&packageHash=fcee790bbc197889231a96be42defc895946cdec2ddb5ca21d9a97df81073a7e&isCompanion=&label=v7&clientUniqueId=87a9a7c0fd465e70","method":"GET"},"timestamp":1503047819.28} }'
08-18 11:16:59.337 23247 23303 I cr_LibraryLoader: Expected native library version number "61.0.3163.51", actual native library version number "61.0.3163.51"
08-18 11:17:00.001  1387  1783 V AlarmManager: Triggering alarm #0: 3 when =1907031705 package=androidoperation =*alarm*:android.intent.action.TIME_TICK
08-18 11:17:00.019  1916  1982 I ClockCtrl:  schedule next: 59981
08-18 11:17:00.019  1916  1982 I KeyguardUpdateMonitor: onTimeChanged
08-18 11:17:00.020  1916  1916 I KeyguardIndication: onTimeChanged
08-18 11:17:00.022  1916  1916 I Clock   : onTimeChanged
08-18 11:17:00.036  1916  1916 I DateView: onTimeChanged
08-18 11:17:00.163 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"category":"xhr","type":"http","data":{"status_code":200,"url":"https://codepush.azurewebsites.net/updateCheck?deploymentKey=RLGAz3loD9CxGf0YaU0qBrFZLHCF8f04da60-90f7-443a-99a6-75aa62d73bad&appVersion=0.10.12&packageHash=fcee790bbc197889231a96be42defc895946cdec2ddb5ca21d9a97df81073a7e&isCompanion=&label=v7&clientUniqueId=87a9a7c0fd465e70","method":"GET"},"timestamp":1503047820.16} }'
08-18 11:17:00.186 23247 23279 I ReactNativeJS: [CodePush] App is up to date.
08-18 11:17:00.189 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"[CodePush] App is up to date.","timestamp":1503047820.186} }'code cache capacity to 128KB
08-18 11:17:02.808 23247 23279 I ReactNativeJS: DashboardScreen
08-18 11:17:02.810 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"DashboardScreen","timestamp":1503047822.807} }'
08-18 11:17:02.820 23247 23279 I ReactNativeJS: DashboardOutdoorContainer
08-18 11:17:02.825 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"DashboardOutdoorContainer","timestamp":1503047822.819} }'
08-18 11:17:02.825 23247 23247 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@e777eed
08-18 11:17:02.826 23247 23247 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@9db7122
08-18 11:17:02.836 23247 23279 I ReactNativeJS: NaModule1CardContainer
08-18 11:17:02.846 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"NaModule1CardContainer","timestamp":1503047822.835} }'
08-18 11:17:02.885 23247 23279 I ReactNativeJS: DashboardIndoorContainer
08-18 11:17:02.891 23247 23279 I ReactNativeJS: NaMainCardContainer
08-18 11:17:02.907 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"DashboardIndoorContainer","timestamp":1503047822.885} }'
08-18 11:17:02.915 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"NaMainCardContainer","timestamp":1503047822.891} }'
08-18 11:17:02.922 23247 23279 I ReactNativeJS: DashboardDropdownContainer
08-18 11:17:02.953 12716 23241 E ctxmgr  : [ProducerActiveIntervalImpl]closeActiveInterval: Error: ongoing, trying to close
08-18 11:17:02.954 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"DashboardDropdownContainer","timestamp":1503047822.922} }'
08-18 11:17:02.979 23247 23279 I ReactNativeJS: StationDropdownButton
08-18 11:17:02.982 23247 23280 I react-native-sentry: captureEvent '{ NativeMap: {"level":"log","category":"console","message":"StationDropdownButton","timestamp":1503047822.979} }'

```

**Comment by HazAT** [comment]
@vincejah This should be resolved.
Could it be that your code really has this error and it will always be thrown on startup?

**Comment by vincejah** [comment]
@HazAT my code cannot have this error at startup as one of them is a generated crash that is triggered when clicking on a button.

I'll test with the latest release.

**Comment by vincejah** [comment]
@HazAT The problem occurs again when switching from 0.21.2 to 0.29.0.

**Comment by HazAT** [comment]
@vincejah can you upgrade to `0.30.0` please.

**Comment by vincejah** [comment]
@HazAT 0.30.0 is not proposed by npm (latest available build on npm is 0.29.0)

**Comment by HazAT** [comment]
@vincejah please try again

**Comment by vincejah** [comment]
@HazAT It does not occur on 0.30.0. Thanks

**Comment by dmhood** [comment]
I'm encountering this on our Android app as well--several fixed issues are getting re-reported at startup even across different builds.  Would love a fix/workaround for this as it's eating a lot of our events!

**Comment by itchingpixels** [comment]
Hi! It seems like we're also affected by this. Unfortunately it makes it really confusing to check if a bug has been fixed or not. This almost renders Sentry useless for us...

**Comment by HazAT** [comment]
Hey, sorry it was so quiet around this issue.
I will take a look at it again today.

**Comment by HazAT** [comment]
Can you guys send me links to your events that got sent twice please?

**Comment by itchingpixels** [comment]
Sure! https://sentry.io/drops-t0/drops-react-native/issues/408265228/ << this was an exception we have thrown manually. It has been removed from the codebase at least 3 days ago - around version 3.11 - but it's still showing up in 3.15. We have disabled codepush in order to verify that this is not coming from there.

**Comment by itchingpixels** [comment]
@HazAT : I can see there's an open PR for this. any ETA for merging it in? we're going live soon (within 24 hours - although soft launching), and it'd be great to get accurate crash reports, otherwise we don't know where we're standing.

**Comment by HazAT** [comment]
@itchingpixels So I am having a hard time reproducing this.
Are you able to test it easily? 
If so you can try it by adding this to your `package.json`

`"react-native-sentry": "https://github.com/getsentry/react-native-sentry#bugfix/android-send-event-twice"`

and run `yarn install / npm install`

would love to get feedback

**Comment by itchingpixels** [comment]
sure, happy to, will roll this out tonight

**Comment by itchingpixels** [comment]
will be releasing this in a few hours. will report back later today if we can still reproduce this issue with the latest build! it'll be actually quite easy to verify, we'll have a result in 24 hours.

**Comment by itchingpixels** [comment]
Hi @HazAT:  
A release build fails on the CI & locally (so it's not connected to cached dependencies) with the following error:

FAILURE: Build failed with an exception.

* What went wrong:
Could not list contents of '/Users/mark/Dev/drops-react-native/node_modules/react-native-sentry/appium/example'. Couldn't follow symbolic link.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

this is when using your branch. Do you have any advice?

**Comment by HazAT** [comment]
@itchingpixels Damn it, ok npm is not considering `.npmignore` when installing directly from a branch.
I will check if I can make a prerelease or something, give me a few minutes.

**Comment by HazAT** [comment]
@itchingpixels 
This is a local `npm pack` of the branch uploaded to my dropbox.
You can add this or download it and upload it somewhere else ...

`"react-native-sentry": "https://www.dropbox.com/s/edmziaethn160w9/react-native-sentry-0.31.0.tgz?dl=1"`

Please do not use this for a prod release.

**Comment by itchingpixels** [comment]
You mean we should upload it to somewhere we control it before using it in prod?

**Comment by HazAT** [comment]
First this yes,
and I mean you should try it before releasing it.

**Comment by itchingpixels** [comment]
We've rolled it out to our beta country. will report back later when we have a meaningful amount of data! It'll take longer, since our beta country has a substantially smaller userbase.

**Comment by itchingpixels** [comment]
I'm around 90% certain that this has helped. By Monday, we can say with 99.9%.

**Comment by HazAT** [comment]
Ok, that's good news 👍 
Let's wait until monday until I make a release

**Comment by itchingpixels** [comment]
I can confirm with 99% confidence that this works - none of the already fixed crashes appear with the latest version we've published!

**Comment by HazAT** [comment]
I've just released version `0.32.0` which includes the fix.
Please check the migration guide in the release section since we have a breaking change in there.
