### ISSUE TITLE
Crash in Sentry after Code Push restart [iOS]

### ISSUE THREAD

**Issue by AndrewJack** [getsentry/react-native-sentry#230]
OS:
- [ ]  Windows
- [x]  MacOS
- [x]  Linux

_Platform:_
- [X]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
Node - v8.2.1
Yarn - 0.47.5

├── react@16.0.0-alpha.12
├── react-native@0.47.2
├── react-native-code-push@5.0.0-beta
├── react-native-sentry@0.21.2
├── react-redux@5.0.6
├── redux@3.7.2
├── redux-logger@3.0.6
├── redux-persist@4.9.1
├── redux-thunk@2.2.0
├── reselect@3.0.1
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
   deactivateStacktraceMerging: true,
}).install()
```

---
I have following issue:

We have seen the following crash in production. It occurs after a code push restart, we were thinking maybe Sentry is holding on to a reference?

```
Crashed: io.sentry.RNSentry
0  libobjc.A.dylib                0x189018bb4 objc_loadWeakRetained + 156
1  Example                     0x100246d70 facebook::react::RCTNativeModule::invokeInner(unsigned int, folly::dynamic const&&) + 109060
2  Example                     0x100246c94 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 108840
3  libdispatch.dylib              0x1894529e0 _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x1894529a0 _dispatch_client_callout + 16
5  libdispatch.dylib              0x189460ad4 _dispatch_queue_serial_drain + 928
6  libdispatch.dylib              0x1894562cc _dispatch_queue_invoke + 884
7  libdispatch.dylib              0x189460fa8 _dispatch_queue_override_invoke + 344
8  libdispatch.dylib              0x189462a50 _dispatch_root_queue_drain + 540
9  libdispatch.dylib              0x1894627d0 _dispatch_worker_thread3 + 124
10 libsystem_pthread.dylib        0x18965b100 _pthread_wqthread + 1096
11 libsystem_pthread.dylib        0x18965acac start_wqthread + 4
```

Sorry we don't have any more useful information, any help would be useful.

**Comment by AndrewJack** [comment]
Looks very similar to https://github.com/getsentry/react-native-sentry/issues/228 

We will try the fix.

**Comment by HazAT** [comment]
@AndrewJack Are you sure that Sentry is the cause of the crash?
I fixed a bug in the latest version regarding a similar crash, but only if stack trace merging is active.

**Comment by AndrewJack** [comment]
@HazAT This may be a code push issue. `Crashed: io.sentry.RNSentry` could just be a result of another issue. I still see this issue after disabling the sentry native library.

**Comment by HazAT** [comment]
OK, I will close this now. I've also updated the docs about CodePush since it wasn't complete.
https://docs.sentry.io/clients/react-native/codepush/
