### ISSUE TITLE
Execution failed for task ':app:bundleReleaseJsAndAssetsSentryUpload'.

### ISSUE THREAD

**Issue by aesmon** [getsentry/react-native-sentry#63]
react-native 0.43.4
react-native-sentry 0.8.5
Android assembleRelease

I get this error:
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
error: http error: generic error (403)
:app:bundleReleaseJsAndAssets FAILED
:app:bundleReleaseJsAndAssets (Thread[main,5,main]) completed. Took 48.784 secs.

Works fine with debug version, fails when building for release.

Can't upgrade react-native-sentry to 0.9.0 due to error with sentry-cli-binary

**Comment by HazAT** [comment]
Hey, please upgrade to the latest version.
Make sure you run `react-native link react-native-sentry`, it seems that you have the wrong credentials.

**Comment by wisedrette** [comment]
Sorry for writing here. But I actually have similar problem with the latest version. 
That problem occurs during assembleRelease. In debug everything works fine, iOS builds don't seem to have such problem as well.

react-native 0.43.4
react-native-sentry 0.11.7
sentry-cli-binary 1.13.1

At first there was a mentioned issue with sentry-cli-binary

I'm not sure whether this issue persists on Linux OS but it's definitely is on Windows. 
So I suppose that line 63 in sentry.gradle should look next way at least for Windows:
`    def cliExecutable = sentryProps.get("cli.executable", "$reactRoot/node_modules/sentry-cli-binary/sentry-cli");
`
I.e. 'bin' part should be removed as actual sentry-cli is located in sentry-cli-binary/sentry-cli

Although it's clear how that one can be hot-fixed and what is exact problem there, the next one is not that simple:
```
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
error: http error: Authentication credentials were not provided. (401)

```
It occurs despite the fact that I have correct credentials in android/sentry.properties file. For iOS sentry with the same credentials and sentry.properties file is working.

**Comment by HazAT** [comment]
Fixed in `0.12.5`

**Comment by nenti** [comment]
@HazAT Thank you for quick fix. I tested your change and it didn't fix the problem for me.

```
Der Befehl "C:\Users\piust\Documents\app/node_modules/sentry-cli-binary/bin/sentry-cli" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\piust\Documents\app\node_modules\react-native-sentry\sentry.gradle' line: 115

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssetsSentryUpload'.
> Process 'command 'cmd'' finished with non-zero exit value 1
```

**Comment by spencerapplegate** [comment]
@HazAT getting same 403 error as @aesmon with the following versions
- react-native 0.44.0
- react-native-sentry 0.13.1
- sentry-cli-binary 1.16.0

**Comment by egormerkushev** [comment]
I think this error means that there is the same file on the server. But why it fails a build? WHY?!

**Comment by quantumpotato** [comment]
Hello, seeing this occur with `"react-native-sentry": "~0.41.1",`
